// app/dashboard/student/odontograms/page.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { SmileIcon as Tooth, Baby, Users, ArrowRight, Calendar, FileText, Plus } from "lucide-react"
import Link from "next/link"

const odontogramTypes = [
  {
    id: "adult",
    title: "Odontograma Adulto",
    description: "Dentición permanente completa (32 dientes)",
    icon: Tooth,
    color: "from-blue-500 to-blue-600",
    teeth: 32,
    ageRange: "18+ años",
    href: "/dashboard/student/odontograms/adult",
    features: ["Sistema FDI", "32 dientes permanentes", "Cuadrantes 1-4"],
  },
  {
    id: "pediatric",
    title: "Odontograma Pediátrico",
    description: "Dentición temporal (20 dientes de leche)",
    icon: Baby,
    color: "from-green-500 to-green-600",
    teeth: 20,
    ageRange: "2-6 años",
    href: "/dashboard/student/odontograms/pediatric",
    features: ["Dientes temporales", "20 dientes de leche", "Cuadrantes 5-8"],
  },
  {
    id: "mixed",
    title: "Odontograma Mixto",
    description: "Dentición mixta (temporal y permanente)",
    icon: Users,
    color: "from-purple-500 to-purple-600",
    teeth: "Variable",
    ageRange: "6-12 años",
    href: "/dashboard/student/odontograms/mixed",
    features: ["Dentición mixta", "Temporales + Permanentes", "Transición dental"],
  },
]

const recentOdontograms = [
  {
    id: 1,
    patientName: "Ana García",
    type: "Adulto",
    date: "2024-01-15",
    status: "Completado",
    progress: 100,
  },
  {
    id: 2,
    patientName: "Carlos López Jr.",
    type: "Pediátrico",
    date: "2024-01-14",
    status: "En progreso",
    progress: 75,
  },
  {
    id: 3,
    patientName: "María Fernández",
    type: "Mixto",
    date: "2024-01-13",
    status: "Pendiente revisión",
    progress: 90,
  },
]

export default function StudentOdontogramsPage() {
  return (
    <div className="space-y-6 p-6">
      <div className="fade-in">
        <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          Odontogramas - Estudiante
        </h1>
        <p className="text-blue-600 mt-2">Crea y gestiona odontogramas para todos los tipos de dentición</p>
      </div>

      {/* Tipos de Odontogramas */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {odontogramTypes.map((type) => {
          const Icon = type.icon
          return (
            <Card key={type.id} className="medical-card group hover:scale-105">
              <CardHeader className="pb-3">
                <div className={`p-4 rounded-lg bg-gradient-to-r ${type.color} w-fit`}>
                  <Icon className="h-8 w-8 text-white" />
                </div>
                <CardTitle className="text-xl font-bold text-blue-800">{type.title}</CardTitle>
                <CardDescription className="text-blue-600">{type.description}</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-blue-500 font-medium">Dientes:</span>
                    <div className="font-bold text-blue-800">{type.teeth}</div>
                  </div>
                  <div>
                    <span className="text-blue-500 font-medium">Edad:</span>
                    <div className="font-bold text-blue-800">{type.ageRange}</div>
                  </div>
                </div>

                <div className="space-y-2">
                  {type.features.map((feature, index) => (
                    <div key={index} className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                      <span className="text-sm text-blue-700">{feature}</span>
                    </div>
                  ))}
                </div>

                <div className="flex gap-2">
                  <Badge variant="secondary" className="text-xs bg-blue-100 text-blue-700">
                    Estándar FDI
                  </Badge>
                  <Badge variant="outline" className="text-xs border-blue-300 text-blue-700">
                    Interactivo
                  </Badge>
                </div>

                <Link href={type.href}>
                  <Button className="w-full btn-medical group-hover:shadow-xl">
                    Crear Odontograma
                    <ArrowRight className="h-4 w-4 ml-2 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Odontogramas Recientes */}
      <Card className="medical-card">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-blue-800">Odontogramas Recientes</CardTitle>
            <CardDescription className="text-blue-600">Últimos odontogramas trabajados</CardDescription>
          </div>
          <Button className="btn-medical">
            <Plus className="h-4 w-4 mr-2" />
            Nuevo Odontograma
          </Button>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {recentOdontograms.map((odontogram) => (
              <div
                key={odontogram.id}
                className="flex items-center justify-between p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border border-blue-200"
              >
                <div className="flex items-center space-x-4">
                  <div className="p-3 bg-blue-100 rounded-full">
                    <Tooth className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-medium text-blue-800">{odontogram.patientName}</p>
                    <p className="text-sm text-blue-600">
                      Tipo: {odontogram.type} • {odontogram.date}
                    </p>
                  </div>
                </div>
                <div className="flex items-center space-x-4">
                  <div className="text-right">
                    <Badge
                      variant={odontogram.status === "Completado" ? "default" : "secondary"}
                      className={
                        odontogram.status === "Completado"
                          ? "bg-green-100 text-green-700"
                          : odontogram.status === "En progreso"
                            ? "bg-blue-100 text-blue-700"
                            : "bg-yellow-100 text-yellow-700"
                      }
                    >
                      {odontogram.status}
                    </Badge>
                    <p className="text-xs text-blue-600 mt-1">{odontogram.progress}% completado</p>
                  </div>
                  <Button variant="outline" size="sm" className="border-blue-300 text-blue-700 hover:bg-blue-50">
                    Ver
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Información del Sistema FDI */}
      <div className="grid gap-6 md:grid-cols-2">
        <Card className="medical-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-blue-800">
              <FileText className="h-5 w-5 text-blue-500" />
              Sistema de Numeración FDI
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm text-blue-700">
            <p>El sistema FDI es el estándar internacional para identificar dientes humanos.</p>
            <div className="space-y-2">
              <div className="p-2 bg-blue-50 rounded">
                <strong>Dentición Permanente:</strong>
                <ul className="mt-1 space-y-1 list-disc list-inside text-blue-600">
                  <li>Cuadrante 1: Maxilar derecho (11-18)</li>
                  <li>Cuadrante 2: Maxilar izquierdo (21-28)</li>
                  <li>Cuadrante 3: Mandíbula izquierda (31-38)</li>
                  <li>Cuadrante 4: Mandíbula derecha (41-48)</li>
                </ul>
              </div>
              <div className="p-2 bg-green-50 rounded">
                <strong>Dentición Temporal:</strong>
                <ul className="mt-1 space-y-1 list-disc list-inside text-green-600">
                  <li>Cuadrante 5: Maxilar derecho (51-55)</li>
                  <li>Cuadrante 6: Maxilar izquierdo (61-65)</li>
                  <li>Cuadrante 7: Mandíbula izquierda (71-75)</li>
                  <li>Cuadrante 8: Mandíbula derecha (81-85)</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="medical-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-blue-800">
              <Calendar className="h-5 w-5 text-green-500" />
              Estados Dentales
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="grid grid-cols-2 gap-3">
              <div className="flex items-center gap-2">
                <div className="tooth tooth-healthy">S</div>
                <span className="text-blue-700">Sano</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-caries">C</div>
                <span className="text-blue-700">Caries</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-filled">O</div>
                <span className="text-blue-700">Obturado</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-crown">Co</div>
                <span className="text-blue-700">Corona</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-missing">X</div>
                <span className="text-blue-700">Ausente</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-root-canal">E</div>
                <span className="text-blue-700">Endodoncia</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="tooth tooth-implant">I</div>
                <span className="text-blue-700">Implante</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// src/views/dashboard/student/Odontograms.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold text-green-800">Odontogramas</h1>
      <p class="text-green-600">Herramientas de diagnóstico dental para diferentes tipos de dentición</p>
    </div>

    <!-- Odontogram Types -->
    <div class="grid gap-6 md:grid-cols-3">
      <div class="bg-white rounded-lg border border-green-200 shadow-sm overflow-hidden">
        <div class="p-6">
          <div class="flex items-center justify-center w-16 h-16 bg-blue-100 rounded-lg mb-4 mx-auto">
            <User class="h-8 w-8 text-blue-600" />
          </div>
          <h3 class="text-xl font-semibold text-center text-gray-900 mb-2">Odontograma Adulto</h3>
          <p class="text-gray-600 text-center mb-4">Dentición permanente completa (32 dientes)</p>
          <div class="text-center">
            <button 
              @click="openOdontogram('adult')"
              class="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-md transition-colors"
            >
              Abrir Odontograma
            </button>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-lg border border-green-200 shadow-sm overflow-hidden">
        <div class="p-6">
          <div class="flex items-center justify-center w-16 h-16 bg-green-100 rounded-lg mb-4 mx-auto">
            <Baby class="h-8 w-8 text-green-600" />
          </div>
          <h3 class="text-xl font-semibold text-center text-gray-900 mb-2">Odontograma Pediátrico</h3>
          <p class="text-gray-600 text-center mb-4">Dentición temporal (20 dientes)</p>
          <div class="text-center">
            <button 
              @click="openOdontogram('pediatric')"
              class="w-full bg-green-600 hover:bg-green-700 text-white py-2 px-4 rounded-md transition-colors"
            >
              Abrir Odontograma
            </button>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-lg border border-green-200 shadow-sm overflow-hidden">
        <div class="p-6">
          <div class="flex items-center justify-center w-16 h-16 bg-purple-100 rounded-lg mb-4 mx-auto">
            <Users class="h-8 w-8 text-purple-600" />
          </div>
          <h3 class="text-xl font-semibold text-center text-gray-900 mb-2">Odontograma Mixto</h3>
          <p class="text-gray-600 text-center mb-4">Dentición mixta (temporal y permanente)</p>
          <div class="text-center">
            <button 
              @click="openOdontogram('mixed')"
              class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md transition-colors"
            >
              Abrir Odontograma
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Recent Odontograms -->
    <div class="bg-white rounded-lg border border-green-200 shadow-sm">
      <div class="p-6 border-b border-green-200">
        <h2 class="text-xl font-semibold text-green-800 flex items-center gap-2">
          <FileText class="h-5 w-5" />
          Odontogramas Recientes
        </h2>
      </div>
      <div class="p-6">
        <div v-if="recentOdontograms.length === 0" class="text-center py-8">
          <FileText class="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <p class="text-gray-600">No hay odontogramas guardados</p>
        </div>
        <div v-else class="space-y-4">
          <div v-for="odontogram in recentOdontograms" :key="odontogram.id" 
               class="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-4">
                <div :class="`w-12 h-12 rounded-lg flex items-center justify-center ${getTypeColor(odontogram.type)}`">
                  <component :is="getTypeIcon(odontogram.type)" class="h-6 w-6 text-white" />
                </div>
                <div>
                  <h3 class="font-medium text-gray-900">{{ odontogram.patientName }}</h3>
                  <p class="text-sm text-gray-600">{{ getTypeLabel(odontogram.type) }} • {{ odontogram.date }}</p>
                  <p class="text-xs text-gray-500">{{ odontogram.findings }} hallazgos registrados</p>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <button 
                  @click="viewOdontogram(odontogram)"
                  class="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded text-sm transition-colors"
                >
                  Ver
                </button>
                <button 
                  @click="editOdontogram(odontogram)"
                  class="bg-green-600 hover:bg-green-700 text-white px-3 py-1 rounded text-sm transition-colors"
                >
                  Editar
                </button>
                <button 
                  @click="exportOdontogram(odontogram)"
                  class="border border-gray-300 text-gray-700 hover:bg-gray-50 px-3 py-1 rounded text-sm transition-colors"
                >
                  Exportar
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Quick Stats -->
    <div class="grid gap-6 md:grid-cols-4">
      <div class="bg-white rounded-lg border border-blue-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-blue-800">Odontogramas Adulto</p>
            <p class="text-2xl font-bold text-blue-700">{{ stats.adult }}</p>
          </div>
          <User class="h-8 w-8 text-blue-600" />
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-green-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-green-800">Odontogramas Pediátricos</p>
            <p class="text-2xl font-bold text-green-700">{{ stats.pediatric }}</p>
          </div>
          <Baby class="h-8 w-8 text-green-600" />
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-purple-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-purple-800">Odontogramas Mixtos</p>
            <p class="text-2xl font-bold text-purple-700">{{ stats.mixed }}</p>
          </div>
          <Users class="h-8 w-8 text-purple-600" />
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-orange-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-orange-800">Total Hallazgos</p>
            <p class="text-2xl font-bold text-orange-700">{{ stats.totalFindings }}</p>
          </div>
          <Search class="h-8 w-8 text-orange-600" />
        </div>
      </div>
    </div>

    <!-- Odontogram Modal -->
    <div v-if="showOdontogramModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div class="bg-white rounded-lg w-full max-w-6xl mx-4 max-h-[95vh] overflow-hidden">
        <div class="flex items-center justify-between p-6 border-b border-gray-200">
          <div>
            <h3 class="text-lg font-semibold text-gray-900">
              {{ getTypeLabel(currentOdontogramType) }}
            </h3>
            <p class="text-sm text-gray-600">{{ currentPatient || 'Nuevo odontograma' }}</p>
          </div>
          <div class="flex items-center gap-2">
            <button 
              @click="saveOdontogram"
              class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-md text-sm transition-colors"
            >
              Guardar
            </button>
            <button 
              @click="exportCurrentOdontogram"
              class="border border-gray-300 text-gray-700 hover:bg-gray-50 px-4 py-2 rounded-md text-sm transition-colors"
            >
              Exportar
            </button>
            <button @click="showOdontogramModal = false" class="text-gray-400 hover:text-gray-600">
              <X class="h-6 w-6" />
            </button>
          </div>
        </div>
        
        <div class="p-6 overflow-y-auto max-h-[calc(95vh-120px)]">
          <!-- Interactive Odontogram Component would go here -->
          <div class="bg-gray-100 rounded-lg p-8 text-center">
            <Stethoscope class="h-16 w-16 text-gray-400 mx-auto mb-4" />
            <h4 class="text-lg font-medium text-gray-700 mb-2">Odontograma Interactivo</h4>
            <p class="text-gray-600 mb-4">
              {{ getOdontogramDescription(currentOdontogramType) }}
            </p>
            <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4 max-w-2xl mx-auto">
              <div class="bg-white rounded-lg p-4 border border-gray-200">
                <div class="w-8 h-8 bg-red-500 rounded-full mx-auto mb-2"></div>
                <p class="text-xs text-gray-600">Caries</p>
              </div>
              <div class="bg-white rounded-lg p-4 border border-gray-200">
                <div class="w-8 h-8 bg-blue-500 rounded-full mx-auto mb-2"></div>
                <p class="text-xs text-gray-600">Obturación</p>
              </div>
              <div class="bg-white rounded-lg p-4 border border-gray-200">
                <div class="w-8 h-8 bg-yellow-500 rounded-full mx-auto mb-2"></div>
                <p class="text-xs text-gray-600">Corona</p>
              </div>
              <div class="bg-white rounded-lg p-4 border border-gray-200">
                <div class="w-8 h-8 bg-gray-500 rounded-full mx-auto mb-2"></div>
                <p class="text-xs text-gray-600">Ausente</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { User, Users, FileText, Search, X, Stethoscope, Baby } from 'lucide-vue-next'

const showOdontogramModal = ref(false)
const currentOdontogramType = ref('')
const currentPatient = ref('')

const stats = ref({
  adult: 12,
  pediatric: 8,
  mixed: 5,
  totalFindings: 147
})

const recentOdontograms = ref([
  {
    id: 1,
    patientName: 'María García',
    type: 'adult',
    date: '15 Ene 2025',
    findings: 8
  },
  {
    id: 2,
    patientName: 'Carlos López (7 años)',
    type: 'pediatric',
    date: '14 Ene 2025',
    findings: 3
  },
  {
    id: 3,
    patientName: 'Ana Martínez (9 años)',
    type: 'mixed',
    date: '13 Ene 2025',
    findings: 5
  }
])

const openOdontogram = (type) => {
  currentOdontogramType.value = type
  currentPatient.value = ''
  showOdontogramModal.value = true
}

const viewOdontogram = (odontogram) => {
  currentOdontogramType.value = odontogram.type
  currentPatient.value = odontogram.patientName
  showOdontogramModal.value = true
}

const editOdontogram = (odontogram) => {
  currentOdontogramType.value = odontogram.type
  currentPatient.value = odontogram.patientName
  showOdontogramModal.value = true
}

const exportOdontogram = (odontogram) => {
  alert(`Exportando odontograma de ${odontogram.patientName}`)
}

const saveOdontogram = () => {
  alert('Odontograma guardado exitosamente')
  showOdontogramModal.value = false
}

const exportCurrentOdontogram = () => {
  alert('Exportando odontograma actual')
}

const getTypeColor = (type) => {
  switch (type) {
    case 'adult':
      return 'bg-blue-600'
    case 'pediatric':
      return 'bg-green-600'
    case 'mixed':
      return 'bg-purple-600'
    default:
      return 'bg-gray-600'
  }
}

const getTypeIcon = (type) => {
  switch (type) {
    case 'adult':
      return User
    case 'pediatric':
      return Baby
    case 'mixed':
      return Users
    default:
      return User
  }
}

const getTypeLabel = (type) => {
  switch (type) {
    case 'adult':
      return 'Odontograma Adulto'
    case 'pediatric':
      return 'Odontograma Pediátrico'
    case 'mixed':
      return 'Odontograma Mixto'
    default:
      return 'Odontograma'
  }
}

const getOdontogramDescription = (type) => {
  switch (type) {
    case 'adult':
      return 'Dentición permanente completa con 32 dientes. Haz clic en cada diente para registrar hallazgos clínicos.'
    case 'pediatric':
      return 'Dentición temporal con 20 dientes. Ideal para pacientes de 2 a 6 años aproximadamente.'
    case 'mixed':
      return 'Dentición mixta combinando dientes temporales y permanentes. Para pacientes de 6 a 12 años.'
    default:
      return 'Selecciona un tipo de odontograma para comenzar.'
  }
}
</script>
