// app/dashboard/secretary/page.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Calendar, Users, Clock, Phone, UserPlus, TrendingUp, AlertCircle, CheckCircle, XCircle } from "lucide-react"

export default function SecretaryDashboard() {
  const [stats] = useState({
    todayAppointments: 12,
    pendingApprovals: 5,
    totalPatients: 248,
    weeklyAppointments: 67,
  })

  const [todayAppointments] = useState([
    {
      id: "1",
      time: "09:00",
      patient: "María González",
      student: "Juan Pérez",
      specialty: "Endodoncia",
      status: "confirmada",
    },
    {
      id: "2",
      time: "10:30",
      patient: "Carlos Ruiz",
      student: "Ana López",
      specialty: "Ortodoncia",
      status: "pendiente",
    },
    {
      id: "3",
      time: "14:00",
      patient: "Laura Martínez",
      student: "Pedro Silva",
      specialty: "Cirugía Oral",
      status: "confirmada",
    },
    {
      id: "4",
      time: "15:30",
      patient: "Roberto Díaz",
      student: "Carmen Torres",
      specialty: "Periodoncia",
      status: "cancelada",
    },
  ])

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "confirmada":
        return (
          <Badge variant="default" className="bg-green-100 text-green-800">
            <CheckCircle className="w-3 h-3 mr-1" />
            Confirmada
          </Badge>
        )
      case "pendiente":
        return (
          <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">
            <AlertCircle className="w-3 h-3 mr-1" />
            Pendiente
          </Badge>
        )
      case "cancelada":
        return (
          <Badge variant="destructive" className="bg-red-100 text-red-800">
            <XCircle className="w-3 h-3 mr-1" />
            Cancelada
          </Badge>
        )
      default:
        return <Badge variant="outline">{status}</Badge>
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Panel de Secretaría</h1>
        <p className="text-gray-600 mt-2">Gestiona citas, pacientes y comunicaciones</p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Citas Hoy</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.todayAppointments}</div>
            <p className="text-xs text-muted-foreground">+2 desde ayer</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Pacientes Totales</CardTitle>
            <Users className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.totalPatients}</div>
            <p className="text-xs text-muted-foreground">+12 este mes</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Aprobaciones Pendientes</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.pendingApprovals}</div>
            <p className="text-xs text-muted-foreground">Requieren atención</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Citas Semanales</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.weeklyAppointments}</div>
            <p className="text-xs text-muted-foreground">+15% vs semana anterior</p>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Acciones Rápidas</CardTitle>
          <CardDescription>Tareas frecuentes de secretaría</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Link href="/dashboard/secretary/appointments/create">
              <Button className="w-full h-20 flex flex-col items-center justify-center space-y-2">
                <Calendar className="h-6 w-6" />
                <span>Nueva Cita</span>
              </Button>
            </Link>

            <Link href="/dashboard/secretary/patient-registration">
              <Button
                variant="outline"
                className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
              >
                <UserPlus className="h-6 w-6" />
                <span>Registrar Paciente</span>
              </Button>
            </Link>

            <Link href="/dashboard/secretary/daily-agenda">
              <Button
                variant="outline"
                className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
              >
                <Clock className="h-6 w-6" />
                <span>Agenda Diaria</span>
              </Button>
            </Link>

            <Link href="/dashboard/secretary/communications">
              <Button
                variant="outline"
                className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
              >
                <Phone className="h-6 w-6" />
                <span>Comunicaciones</span>
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* Today's Appointments */}
      <Card>
        <CardHeader>
          <CardTitle>Citas de Hoy</CardTitle>
          <CardDescription>Agenda del día actual</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {todayAppointments.map((appointment) => (
              <div key={appointment.id} className="flex items-center justify-between p-4 border rounded-lg">
                <div className="flex items-center space-x-4">
                  <div className="text-sm font-medium text-blue-600">{appointment.time}</div>
                  <div>
                    <p className="font-medium">{appointment.patient}</p>
                    <p className="text-sm text-gray-600">
                      Estudiante: {appointment.student} • {appointment.specialty}
                    </p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  {getStatusBadge(appointment.status)}
                  <Button variant="ghost" size="sm">
                    Ver detalles
                  </Button>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 pt-4 border-t">
            <Link href="/dashboard/secretary/appointments">
              <Button variant="outline" className="w-full bg-transparent">
                Ver todas las citas
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* Recent Activity */}
      <Card>
        <CardHeader>
          <CardTitle>Actividad Reciente</CardTitle>
          <CardDescription>Últimas acciones realizadas</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <p className="text-sm">
                <span className="font-medium">María González</span> confirmó su cita para mañana
              </p>
              <span className="text-xs text-gray-500 ml-auto">Hace 5 min</span>
            </div>

            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <p className="text-sm">
                Nuevo paciente <span className="font-medium">Carlos Ruiz</span> registrado
              </p>
              <span className="text-xs text-gray-500 ml-auto">Hace 15 min</span>
            </div>

            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-yellow-500 rounded-full"></div>
              <p className="text-sm">
                Cita de <span className="font-medium">Laura Martínez</span> reprogramada
              </p>
              <span className="text-xs text-gray-500 ml-auto">Hace 30 min</span>
            </div>

            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-red-500 rounded-full"></div>
              <p className="text-sm">
                <span className="font-medium">Roberto Díaz</span> canceló su cita
              </p>
              <span className="text-xs text-gray-500 ml-auto">Hace 1 hora</span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// src/views/dashboard/secretary/Secretary.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold text-green-800">Panel de Secretaría</h1>
      <p class="text-green-600">Gestión de pacientes y asignaciones</p>
    </div>

    <!-- Stats Cards -->
    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
      <div class="bg-white rounded-lg border border-green-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-green-800">Pacientes Registrados</p>
            <p class="text-2xl font-bold text-green-700">{{ stats.totalPatients }}</p>
          </div>
          <Users class="h-8 w-8 text-green-600" />
        </div>
        <div class="mt-2 text-xs text-green-600">
          +{{ stats.newPatientsThisWeek }} esta semana
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-blue-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-blue-800">Asignaciones Pendientes</p>
            <p class="text-2xl font-bold text-blue-700">{{ stats.pendingAssignments }}</p>
          </div>
          <UserPlus class="h-8 w-8 text-blue-600" />
        </div>
        <div class="mt-2 text-xs text-blue-600">
          Requieren atención
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-purple-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-purple-800">Citas Hoy</p>
            <p class="text-2xl font-bold text-purple-700">{{ stats.appointmentsToday }}</p>
          </div>
          <Calendar class="h-8 w-8 text-purple-600" />
        </div>
        <div class="mt-2 text-xs text-purple-600">
          {{ stats.appointmentsTomorrow }} mañana
        </div>
      </div>
      
      <div class="bg-white rounded-lg border border-orange-200 shadow-sm p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-orange-800">Estudiantes Activos</p>
            <p class="text-2xl font-bold text-orange-700">{{ stats.activeStudents }}</p>
          </div>
          <GraduationCap class="h-8 w-8 text-orange-600" />
        </div>
        <div class="mt-2 text-xs text-orange-600">
          Disponibles para asignación
        </div>
      </div>
    </div>

    <!-- Quick Actions -->
    <div class="bg-white rounded-lg border border-green-200 shadow-sm">
      <div class="p-6 border-b border-green-200">
        <h2 class="text-xl font-semibold text-green-800 flex items-center gap-2">
          <Zap class="h-5 w-5" />
          Acciones Rápidas
        </h2>
      </div>
      <div class="p-6">
        <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <router-link to="/dashboard/secretary/patient-assignment">
            <button class="w-full p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                  <UserPlus class="h-5 w-5 text-blue-600" />
                </div>
                <div>
                  <h3 class="font-medium text-gray-900">Asignar Paciente</h3>
                  <p class="text-sm text-gray-600">Asignar paciente a estudiante</p>
                </div>
              </div>
            </button>
          </router-link>
          
          <router-link to="/dashboard/secretary/schedule">
            <button class="w-full p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center">
                  <Calendar class="h-5 w-5 text-green-600" />
                </div>
                <div>
                  <h3 class="font-medium text-gray-900">Ver Horarios</h3>
                  <p class="text-sm text-gray-600">Gestionar horarios y citas</p>
                </div>
              </div>
            </button>
          </router-link>
          
          <button class="w-full p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center">
                <FileText class="h-5 w-5 text-purple-600" />
              </div>
              <div>
                <h3 class="font-medium text-gray-900">Generar Reporte</h3>
                <p class="text-sm text-gray-600">Reportes de asignaciones</p>
              </div>
            </div>
          </button>
        </div>
      </div>
    </div>

    <!-- Recent Activity -->
    <div class="bg-white rounded-lg border border-green-200 shadow-sm">
      <div class="p-6 border-b border-green-200">
        <h2 class="text-xl font-semibold text-green-800 flex items-center gap-2">
          <Activity class="h-5 w-5" />
          Actividad Reciente
        </h2>
      </div>
      <div class="p-6">
        <div class="space-y-4">
          <div v-for="activity in recentActivity" :key="activity.id" 
               class="flex items-start gap-3 p-3 border border-gray-200 rounded-lg">
            <div :class="`w-8 h-8 rounded-full flex items-center justify-center ${activity.color}`">
              <component :is="activity.icon" class="h-4 w-4 text-white" />
            </div>
            <div class="flex-1">
              <p class="text-sm font-medium text-gray-900">{{ activity.title }}</p>
              <p class="text-xs text-gray-600">{{ activity.description }}</p>
              <p class="text-xs text-gray-500 mt-1">{{ activity.timestamp }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { Users, UserPlus, Calendar, GraduationCap, Zap, FileText, Activity, User, CheckCircle, AlertCircle } from 'lucide-vue-next'

const stats = ref({
  totalPatients: 156,
  newPatientsThisWeek: 8,
  pendingAssignments: 12,
  appointmentsToday: 24,
  appointmentsTomorrow: 18,
  activeStudents: 45
})

const recentActivity = ref([
  {
    id: 1,
    title: 'Paciente asignado',
    description: 'María García asignada a Juan Pérez',
    timestamp: 'Hace 15 minutos',
    icon: User,
    color: 'bg-blue-600'
  },
  {
    id: 2,
    title: 'Cita programada',
    description: 'Cita para Carlos López - 15 Ene, 10:00 AM',
    timestamp: 'Hace 30 minutos',
    icon: Calendar,
    color: 'bg-green-600'
  },
  {
    id: 3,
    title: 'Asignación completada',
    description: 'Ana Martínez completó tratamiento',
    timestamp: 'Hace 1 hora',
    icon: CheckCircle,
    color: 'bg-purple-600'
  },
  {
    id: 4,
    title: 'Conflicto de horario',
    description: 'Conflicto detectado en horario de Pedro Gómez',
    timestamp: 'Hace 2 horas',
    icon: AlertCircle,
    color: 'bg-red-600'
  }
])
</script>
